name: Build and Commit Portable App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyautogui pyinstaller pillow pystray

      - name: Build with PyInstaller
        run: |
          pyinstaller --name "UtillBuddy-${{ matrix.os }}" --onefile main.py

      - name: Move build to dist folder
        run: |
          mkdir -p portable/${{ matrix.os }}
          cp dist/UtillBuddy-${{ matrix.os }}* portable/${{ matrix.os }}/

      - name: Commit built files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add portable/${{ matrix.os }}
          git commit -m "Add portable build for ${{ matrix.os }} [auto]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
