name: Build, Upload Artifacts, and Commit All

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            label: Linux
            ext: ""
          - os: windows-latest
            label: Windows
            ext: ".exe"
          - os: macos-latest
            label: macOS
            ext: ".app"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyautogui pyinstaller pystray pillow

      - name: Build portable app
        run: |
          pyinstaller --name "UtillBuddy${{ matrix.ext }}" --onefile utill_buddy.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: portable-${{ matrix.label }}
          path: dist/UtillBuddy${{ matrix.ext }}

  commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: portable-Linux
          path: portable/Linux
      - uses: actions/download-artifact@v3
        with:
          name: portable-Windows
          path: portable/Windows
      - uses: actions/download-artifact@v3
        with:
          name: portable-macOS
          path: portable/macOS

      - name: Update README.md with download links
        run: |
          START="<!-- BUILDS START -->"
          END="<!-- BUILDS END -->"
          # Prepare download links
          LINKS="
          🔹 [Download for Linux](portable/Linux/UtillBuddy)
          🔹 [Download for Windows](portable/Windows/UtillBuddy.exe)
          🔹 [Download for macOS](portable/macOS/UtillBuddy.app)
          "
          # Replace content between markers
          awk -v s="$START" -v e="$END" -v l="$LINKS" '
            $0 ~ s { print; print l; skip=1; next }
            $0 ~ e { skip=0 }
            skip == 0 { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit all builds and updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add portable README.md
          git commit -m "Add all platform builds and update README [auto]" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
